version: '3.8'

services:
  api:
    container_name: nestjs_api
    image: nestjs-api:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
  pgsql:
    image: postgres:alpine
    ports:
      - 5432:5432
    container_name: 'postgres'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - nesjs-network
networks:
  nesjs-network: null
volumes:
  pg-data: null
